@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

left to right direction

' Classes
abstract class Veiculo {
    - autonomia: Double
}

class Localidade {
    - nome: String
}

class PercursoMinimo {
    - localOrigem: Localidade
    - locaisPassagem: List<Localidade>
    - distanciasEntreLocais: Map<Localidade, Double>
    - localDestino: Localidade
    - distanciaTotal: Double
    - numeroCarregamentos: int
}

' Associações
Veiculo "1" --> "1..*" PercursoMinimo : determina >
PercursoMinimo --* Localidade : inclui >

@enduml
