@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

interface Runnable{
+run()
}

class RegisterPruningUI{
+run()
-getOperatID()
-getParcelID()
-getVarietyID()
-getExecMethodID()
-registerPruning()
}

class RegisterPruningCtrl{
+getParcels()
+getVarieties()
+getExecMethods()
+registerPruning()
}

class AgrOperatDataAccess{
+getNextAgrOperatID()
}

class ParcelsDataAccess{
+getParcels()
}

class VarietiesDataAccess{
+getVarieties()
}

class ExecMethodsDataAccess{
+getExecMethods()
}

class PruningsDataAccess{
+registerPruning()
}

Runnable<|.r.RegisterPruningUI

RegisterPruningUI<.d.RegisterPruningCtrl

RegisterPruningCtrl..>AgrOperatDataAccess
RegisterPruningCtrl..>ParcelsDataAccess
RegisterPruningCtrl..>VarietiesDataAccess
RegisterPruningCtrl..>ExecMethodsDataAccess
RegisterPruningCtrl..>PruningsDataAccess


@enduml
