@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US LP08 - Registrar Poda - System Sequence Diagram

autonumber

actor "Gestor Agrícola" as user
participant ":RegisterPruningUI" as ui
participant "ctrl \n :RegisterPruningCtrl" as ctrl
participant ":AgrOperatDataAccess" as agrOperat
participant ":ParcelsDataAccess" as parcels
participant ":VarietiesDataAccess" as varieties
participant ":ExecMethodsDataAccess" as execMethods
participant ":ExecMethodsDataAccess" as execMethods
participant ":PruningsDataAccess" as prunings

activate user
    user -> ui: pede para registrar poda

    activate ui
    ui->ctrl: getOperationID()

    activate ctrl
    ctrl->agrOperat: getLatestID()

    activate agrOperat
    agrOperat-->ctrl:getLatestID
    deactivate

    ctrl-->ui: nextOperationID
    deactivate

    ui-->user: pede para introduzir a data de realização da operação
    deactivate

    user->ui: introduz a data da operação

    activate ui
    ui->ctrl: getParcels()

    activate ctrl
    ctrl->parcels:getParcels()

    activate parcels
    parcels-->ctrl: parcels
    deactivate

    ctrl-->ui: parcels
    deactivate

    ui-->user: lista parcelas registadas no sistema e pede para escolher
    deactivate ui

    user->ui: seleciona a parcela pretendida

    activate ui
        ui->ctrl: getVarieties()

        activate ctrl
        ctrl->varieties:getVarieties()

        activate varieties
        varieties-->ctrl: varieties
        deactivate

        ctrl-->ui: varieties
        deactivate
    ui-->user: lista as variedades presentes na parcela e pede para escolher
    deactivate

    user->ui: seleciona a variedade pretendida

    activate ui
        ui->ctrl: getExecutionMethods()

        activate ctrl
        ctrl->execMethods:getExecutionMethods()

        activate execMethods
        execMethods-->ctrl: executionMethods
        deactivate

        ctrl-->ui: executionMethods
        deactivate
    ui-->user: lista métodos de execução e pede para escolher
    deactivate

    user->ui: seleciona o método pretendido

    activate ui
        ui->ctrl: registerPruning()

        activate ctrl
        ctrl->prunings:registerPruning()

        activate prunings
        prunings-->ctrl: success/insuccess
        deactivate

        ctrl-->ui: success/insuccess
        deactivate
    ui-->user: indica o sucesso ou insucesso da operação
    deactivate

@enduml