@startuml

actor User
actor Scheduler

User -> Scheduler: runRegaProcess(filePath)
activate User
activate Scheduler

Scheduler -> Scheduler: readCSV(filePath)
Scheduler -> Scheduler: registerNextOperation(0)
Scheduler -> Scheduler: scheduleRegaOperation(index, endTime)
Scheduler -> Scheduler: performRegistration(index, operacaoId, regaTable, callback, check)
Scheduler -> User : Informs operation sucess
deactivate Scheduler
deactivate User

@enduml
