@startuml

skinparam SequenceMessageAlign center

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US002

autonumber

actor "Gestor Agrícola" as Gestor
entity "System" as System

activate Gestor

Gestor -> System : solicita lista de fatores de produção aplicados em uma parcela
activate System

System --> Gestor : exibe opções de operações disponíveis e solicita seleção
deactivate System

Gestor -> System : seleciona operação de consulta de fatores de produção
activate System

System --> Gestor : solicita informações específicas da consulta (parcela, intervalo de tempo)
deactivate System

Gestor -> System : fornece informações necessárias (número da parcela, intervalo de tempo, etc.)
activate System

System --> Gestor : retorna lista dos fatores de produção e quantidades para cada substância componente na parcela e intervalo de tempo especificados
deactivate System

Gestor --> System : visualiza a lista dos fatores de produção
deactivate Gestor

@enduml
