@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateAnnoucementController" as Controller

participant ":Repositories" as Repositories
participant "repositories:\nRepositories" as repositoriesInstance
participant "advertisementsRepository\n:AdvertisementsRepository" as advertisementsRepository
participant "leasesRepository\n:LeasesRepository" as leases
participant "lease\n:Lease" as lease
participant "salesRepository\n:SalesRepository" as sales
participant "sale\n:Sale" as sale



autonumber

activate Controller

Controller->Repositories:getInstance()

    activate Repositories
    Repositories-->Controller:repositories
    deactivate Repositories

    Controller->repositoriesInstance:getAdvertisementsRepository()

    activate repositoriesInstance
    repositoriesInstance-->Controller:advertisementsRepository
    deactivate repositoriesInstance

    Controller->advertisementsRepository:getLeasesRepository()

        activate advertisementsRepository
        advertisementsRepository-->Controller:leasesRepository
        deactivate advertisementsRepository

Controller->leases:validateProperty(property)

activate leases

loop for each lease
leases->lease:isThereProperty(property)

activate lease
lease-->leases:true/false
deactivate lease

end

leases-->Controller:true/false
deactivate leases

Controller->Repositories:getInstance()

    activate Repositories
    Repositories-->Controller:repositories
    deactivate Repositories

    Controller->repositoriesInstance:getAdvertisementsRepository()

    activate repositoriesInstance
    repositoriesInstance-->Controller:advertisementsRepository
    deactivate repositoriesInstance


Controller->advertisementsRepository:getSalesRepository()

    activate advertisementsRepository
    advertisementsRepository-->Controller:salesRepository
    deactivate advertisementsRepository

Controller->sales:validateProperty(property)

activate sales

loop for each sale
sales->sale:isThereProperty(property)

activate sale
sale-->sales:true/false
deactivate sale

end

sales-->Controller:true/false
deactivate sales

<--Controller:success

deactivate Controller

@enduml