INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (0, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (1, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (2, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (3, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (4, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (5, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (6, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (7, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (8, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (9, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (10, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (11, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (12, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (13, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (14, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (15, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (16, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (17, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (18, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (19, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (20, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (21, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (22, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (23, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (24, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (25, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (26, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (27, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (28, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (29, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (30, ' Novembro a dezembro ' , ' Fevereiro a março ' , ' Julho a agosto ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (31, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (32, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (33, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (34, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (35, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (36, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (37, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (38, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (39, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (40, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (41, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (42, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (43, ' Janeiro ' , ' Abril a maio ' , ' Novembro a dezembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (44, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (45, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (46, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (47, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (48, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (49, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (50, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (51, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (52, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (53, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (54, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (55, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (56, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (57, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (58, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (59, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (60, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (61, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (62, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (63, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (64, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (65, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (66, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (67, ' Novembro a dezembro ' , ' Março a abril ' , ' Agosto a setembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (68, '  ' , '  ' , '  ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (69, '  ' , '  ' , '  ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (70, '  ' , '  ' , '  ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (71, '  ' , '  ' , '  ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (72, '  ' , ' 80 dias ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (73, '  ' , ' 80 dias ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (74, '  ' , ' 80 dias ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (75, '  ' , ' 80 dias ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (76, '  ' , ' 80 dias ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (77, '  ' , ' 80 dias ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (78, '  ' , ' 80 dias ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (79, '  ' , '  ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (80, '  ' , '  ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (81, ' Abril a junho ' , ' Julho a setembro ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (82, ' Abril a junho ' , ' Julho a setembro ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (83, ' Março a setembro ' , ' Junho a fevereiro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (84, '  ' , ' Outubro a novembro ' , '  ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (85, '  ' , '  ' , ' Outubro a novembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (86, '  ' , '  ' , ' Outubro a novembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (87, '  ' , '  ' , ' Outubro a novembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (88, '  ' , '  ' , ' Outubro a novembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (89, '  ' , '  ' , ' Outubro a novembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (90, '  ' , '  ' , ' Outubro a novembro ' );
INSERT INTO CICLO_PERMANENTE (CICLO_ID,FASE_PODA,FASE_FLORACAO,FASE_COLHEITA) VALUES (91, '  ' , '  ' , ' Outubro a novembro ' );
INSERT INTO CICLO_TEMPORARIA (CICLO_ID,FASE_SEMENTEIRA,FASE_COLHEITA) VALUES (92, ' Fevereiro a abril, agosto a outubro ' , ' 90 dias ' );
