INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (0, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (1, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (2, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (3, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (4, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (5, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (6, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (7, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (8, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (9, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (10, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (11, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (12, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (13, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (14, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (15, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (16, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (17, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (18, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (19, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (20, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (21, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (22, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (23, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (24, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (25, ' Ameixoeira ' , ' Prunus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (26, ' Damasqueiro ' , ' Prunus armeniaca ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (27, ' Damasqueiro ' , ' Prunus armeniaca ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (28, ' Damasqueiro ' , ' Prunus armeniaca ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (29, ' Damasqueiro ' , ' Prunus armeniaca ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (30, ' Damasqueiro ' , ' Prunus armeniaca ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (31, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (32, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (33, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (34, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (35, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (36, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (37, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (38, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (39, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (40, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (41, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (42, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (43, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (44, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (45, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (46, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (47, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (48, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (49, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (50, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (51, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (52, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (53, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (54, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (55, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (56, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (57, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (58, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (59, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (60, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (61, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (62, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (63, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (64, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (65, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (66, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (67, ' Macieira ' , ' Malus domestica ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (68, ' Pera Nashi ' , ' Pyrus pyrifolia ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (69, ' Pera Nashi ' , ' Pyrus pyrifolia ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (70, ' Pera Nashi ' , ' Pyrus pyrifolia ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (71, ' Pera Nashi ' , ' Pyrus pyrifolia ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (72, ' Cenoura ' , ' Daucus carota subsp. Sativus ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (73, ' Cenoura ' , ' Daucus carota subsp. Sativus ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (74, ' Cenoura ' , ' Daucus carota subsp. Sativus ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (75, ' Cenoura ' , ' Daucus carota subsp. Sativus ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (76, ' Cenoura ' , ' Daucus carota subsp. Sativus ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (77, ' Cenoura ' , ' Daucus carota subsp. Sativus ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (78, ' Cenoura ' , ' Daucus carota subsp. Sativus ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (79, ' Tremoço ' , ' Lupinus luteus ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (80, ' Tremoço ' , ' Lupinus albus ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (81, ' Milho ' , ' Zea mays ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (82, ' Milho ' , ' Zea mays ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (83, ' Nabo greleiro ' , ' Brassica rapa ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (84, ' Oliveira ' , ' Olea europaea ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (85, ' Oliveira ' , ' Olea europaea ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (86, ' Oliveira ' , ' Olea europaea ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (87, ' Oliveira ' , ' Olea europaea ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (88, ' Oliveira ' , ' Olea europaea ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (89, ' Oliveira ' , ' Olea europaea ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (90, ' Oliveira ' , ' Olea europaea ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (91, ' Oliveira ' , ' Olea europaea ' ,0);
INSERT INTO Especie (id , nome_comum,nome_cientifico,tipo_consumo_id ) VALUES (92, ' Nabo ' , ' Brassica rapa L. ' ,0);
