@startuml

skinparam SequenceMessageAlign center

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US002

autonumber

actor "Gestor Agrícola" as Gestor
entity "System" as System

activate Gestor
Gestor -> System : pede para registar uma operação de Colheita
activate System

System --> Gestor : pede para inserir a data atual
deactivate System

Gestor -> System : insere a data atual
activate System

System --> Gestor : exibe opções de parcelas possíveis e solicita uma seleção
deactivate System

Gestor -> System : seleciona a parcela
activate System

System --> Gestor : exibe opções de produtos possíveis e solicita uma seleção
deactivate System

Gestor -> System : seleciona o produto
activate System

System --> Gestor : solicita método de execução desejado
deactivate System

Gestor -> System : fornece id do metode de execução desejado
activate System

System --> Gestor : solicita a quantidade
deactivate System

Gestor -> System : insere a quantidade
activate System


System --> Gestor : valida e registra a operação de colheita no sistema
deactivate System

Gestor --> System : confirmação de sucesso no registro
deactivate Gestor

@enduml