@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'direção da esquerda para a direita

skinparam classAttributeIconSize 0
hide circles
hide methods
hide empty members

title Modelo de Domínio - US003
abstract class GestorAgricola {
}

class ConsultaFatoresProducao {
    parcela : Parcela
    intervaloDeTempo
}

class Parcela {
    numero
}

class FatorProducao {
    tipoSubstancia
    quantidade
}

GestorAgricola "1" -right- "1..*" ConsultaFatoresProducao : deseja consultar >
ConsultaFatoresProducao "1" -right- "1" Parcela : na parcela >
ConsultaFatoresProducao "1" -right- "1..*" FatorProducao : com respetivas quantidades de fatores de produção >

@enduml
