INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (1, 'Ameixoeira','Prunus domestica');
INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (2, 'Damasqueiro','Prunus armeniaca');
INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (3, 'Macieira','Malus domestica');
INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (4, 'Pera Nashi','Pyrus pyrifolia');
INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (5, 'Cenoura','Daucus carota subsp. Sativus');
INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (6, 'Tremoço','Lupinus luteus');
INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (6, 'Tremoço','Lupinus albus');
INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (8, 'Milho','Zea mays');
INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (9, 'Nabo greleiro','Brassica rapa');
INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (11, 'Oliveira','Olea europaea');
INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (10, 'Nabo','Brassica rapa');
INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (12, 'Videira','Vitis vinifera');
INSERT INTO Cultura(id,nome_comum,nome_cientifico) values (13, 'Abóbora manteiga','Cucurbita moschata');

INSERT INTO Variedade(id,nome,cultura_id) values (100, 'RAINHA CLAUDIA CARANGUEJEIRA',1);
INSERT INTO Variedade(id,nome,cultura_id) values (101, 'PRESIDENT',1);
INSERT INTO Variedade(id,nome,cultura_id) values (102, 'STANLEY',1);
INSERT INTO Variedade(id,nome,cultura_id) values (103, 'ANGELENO',1);
INSERT INTO Variedade(id,nome,cultura_id) values (104, 'BLACK BEAUTY',1);
INSERT INTO Variedade(id,nome,cultura_id) values (105, 'BLACK STAR',1);
INSERT INTO Variedade(id,nome,cultura_id) values (106, 'BLACK GOLD',1);
INSERT INTO Variedade(id,nome,cultura_id) values (107, 'BLACK DIAMOND',1);
INSERT INTO Variedade(id,nome,cultura_id) values (108, 'BLACK AMBER',1);
INSERT INTO Variedade(id,nome,cultura_id) values (109, 'BLACK SPLENDOR',1);
INSERT INTO Variedade(id,nome,cultura_id) values (110, 'FORTUNA',1);
INSERT INTO Variedade(id,nome,cultura_id) values (111, 'FRIAR',1);
INSERT INTO Variedade(id,nome,cultura_id) values (112, 'EL DORADO',1);
INSERT INTO Variedade(id,nome,cultura_id) values (113, 'ELEPHANT HEART',1);
INSERT INTO Variedade(id,nome,cultura_id) values (114, 'GOLDEN JAPAN',1);
INSERT INTO Variedade(id,nome,cultura_id) values (115, 'HARRY PITCHON',1);
INSERT INTO Variedade(id,nome,cultura_id) values (116, 'LAETITIA',1);
INSERT INTO Variedade(id,nome,cultura_id) values (117, 'METLEY',1);
INSERT INTO Variedade(id,nome,cultura_id) values (118, 'MIRABELLE DE NANCY',1);
INSERT INTO Variedade(id,nome,cultura_id) values (119, 'QUEEN ROSE',1);
INSERT INTO Variedade(id,nome,cultura_id) values (120, 'RED BEAUT',1);
INSERT INTO Variedade(id,nome,cultura_id) values (121, 'SANTA ROSA',1);
INSERT INTO Variedade(id,nome,cultura_id) values (122, 'SHIRO',1);
INSERT INTO Variedade(id,nome,cultura_id) values (123, 'SUNGOLD',1);
INSERT INTO Variedade(id,nome,cultura_id) values (124, 'WILSON PERFECTION',1);
INSERT INTO Variedade(id,nome,cultura_id) values (125, 'AUTUMN GIANT',1);
INSERT INTO Variedade(id,nome,cultura_id) values (126, 'BULIDA',2);
INSERT INTO Variedade(id,nome,cultura_id) values (127, 'CANINO',2);
INSERT INTO Variedade(id,nome,cultura_id) values (128, 'LIABAUD',2);
INSERT INTO Variedade(id,nome,cultura_id) values (129, 'MAILLOT JAUNE',2);
INSERT INTO Variedade(id,nome,cultura_id) values (130, 'POLONAIS',2);
INSERT INTO Variedade(id,nome,cultura_id) values (131, 'AKANE',3);
INSERT INTO Variedade(id,nome,cultura_id) values (132, 'BELGOLDEN',3);
INSERT INTO Variedade(id,nome,cultura_id) values (133, 'BRAVO DE ESMOLFE',3);
INSERT INTO Variedade(id,nome,cultura_id) values (134, 'CASA NOVA DE ALCOBAÇA',3);
INSERT INTO Variedade(id,nome,cultura_id) values (135, 'EROVAN',3);
INSERT INTO Variedade(id,nome,cultura_id) values (136, 'FUJI',3);
INSERT INTO Variedade(id,nome,cultura_id) values (137, 'GRANNY SMITH',3);
INSERT INTO Variedade(id,nome,cultura_id) values (138, 'GOLDEN DELICIOUS',3);
INSERT INTO Variedade(id,nome,cultura_id) values (139, 'HI-EARLY',3);
INSERT INTO Variedade(id,nome,cultura_id) values (140, 'JONAGORED',3);
INSERT INTO Variedade(id,nome,cultura_id) values (141, 'LYSGOLDEN',3);
INSERT INTO Variedade(id,nome,cultura_id) values (142, 'MUTSU',3);
INSERT INTO Variedade(id,nome,cultura_id) values (143, 'PORTA DA LOJA',3);
INSERT INTO Variedade(id,nome,cultura_id) values (144, 'REINETTE OU CANADA',3);
INSERT INTO Variedade(id,nome,cultura_id) values (145, 'REINETTE OU GRAND FAY',3);
INSERT INTO Variedade(id,nome,cultura_id) values (146, 'RISCADINHA DE PALMELA',3);
INSERT INTO Variedade(id,nome,cultura_id) values (147, 'ROYAL GALA',3);
INSERT INTO Variedade(id,nome,cultura_id) values (148, 'REDCHIEF',3);
INSERT INTO Variedade(id,nome,cultura_id) values (149, 'STARKING',3);
INSERT INTO Variedade(id,nome,cultura_id) values (150, 'SUMMER RED',3);
INSERT INTO Variedade(id,nome,cultura_id) values (151, 'WELL SPUR DELICIOUS',3);
INSERT INTO Variedade(id,nome,cultura_id) values (152, 'NOIVA',3);
INSERT INTO Variedade(id,nome,cultura_id) values (153, 'OLHO ABERTO',3);
INSERT INTO Variedade(id,nome,cultura_id) values (154, 'CAMOESA ROSA',3);
INSERT INTO Variedade(id,nome,cultura_id) values (155, 'MALÁPIO',3);
INSERT INTO Variedade(id,nome,cultura_id) values (156, 'GRONHO DOCE',3);
INSERT INTO Variedade(id,nome,cultura_id) values (157, 'PÉ DE BOI ',3);
INSERT INTO Variedade(id,nome,cultura_id) values (158, 'PINOVA',3);
INSERT INTO Variedade(id,nome,cultura_id) values (159, 'PARDO LINDO',3);
INSERT INTO Variedade(id,nome,cultura_id) values (160, 'PIPO DE BASTO',3);
INSERT INTO Variedade(id,nome,cultura_id) values (161, 'PRIMA',3);
INSERT INTO Variedade(id,nome,cultura_id) values (162, 'QUERINA',3);
INSERT INTO Variedade(id,nome,cultura_id) values (163, 'VISTA BELLA',3);
INSERT INTO Variedade(id,nome,cultura_id) values (164, 'GOLDEN SMOOTHEE',3);
INSERT INTO Variedade(id,nome,cultura_id) values (165, 'GOLDEN SUPREMA',3);
INSERT INTO Variedade(id,nome,cultura_id) values (166, 'GLOSTER 69',3);
INSERT INTO Variedade(id,nome,cultura_id) values (167, 'FREEDOM',3);
INSERT INTO Variedade(id,nome,cultura_id) values (168, 'SNINSEIKI',4);
INSERT INTO Variedade(id,nome,cultura_id) values (169, 'KUMOI',4);
INSERT INTO Variedade(id,nome,cultura_id) values (170, 'HOSUI',4);
INSERT INTO Variedade(id,nome,cultura_id) values (171, 'NIJISSEIKI',4);
INSERT INTO Variedade(id,nome,cultura_id) values (172, 'Carson Hybrid',5);
INSERT INTO Variedade(id,nome,cultura_id) values (173, 'Red Cored Chantenay',5);
INSERT INTO Variedade(id,nome,cultura_id) values (174, 'Danvers Half Long',5);
INSERT INTO Variedade(id,nome,cultura_id) values (175, 'Imperator 58',5);
INSERT INTO Variedade(id,nome,cultura_id) values (176, 'Sugarsnax Hybrid',5);
INSERT INTO Variedade(id,nome,cultura_id) values (177, 'Nelson Hybrid',5);
INSERT INTO Variedade(id,nome,cultura_id) values (178, 'Scarlet Nantes',5);
INSERT INTO Variedade(id,nome,cultura_id) values (179, 'Amarelo',6);
INSERT INTO Variedade(id,nome,cultura_id) values (180, 'Branco',6);
INSERT INTO Variedade(id,nome,cultura_id) values (181, 'MAS 24.C',8);
INSERT INTO Variedade(id,nome,cultura_id) values (182, 'Doce Golden Bantam',8);
INSERT INTO Variedade(id,nome,cultura_id) values (183, 'Senhora Conceição',9);
INSERT INTO Variedade(id,nome,cultura_id) values (184, 'COBRANÇOSA',11);
INSERT INTO Variedade(id,nome,cultura_id) values (185, 'ARBEQUINA',11);
INSERT INTO Variedade(id,nome,cultura_id) values (186, 'HOJIBLANCA',11);
INSERT INTO Variedade(id,nome,cultura_id) values (187, 'NEGRINHA DO FREIXO',11);
INSERT INTO Variedade(id,nome,cultura_id) values (188, 'PICUAL',11);
INSERT INTO Variedade(id,nome,cultura_id) values (189, 'MAÇANILHA',11);
INSERT INTO Variedade(id,nome,cultura_id) values (190, 'CONSERVA DE ELVAS',11);
INSERT INTO Variedade(id,nome,cultura_id) values (191, 'GALEGA',11);
INSERT INTO Variedade(id,nome,cultura_id) values (192, 'S. Cosme',10);
INSERT INTO Variedade(id,nome,cultura_id) values (193, 'Dona Maria',12);
INSERT INTO Variedade(id,nome,cultura_id) values (194, 'Cardinal',12);

INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (100, 'RAINHA CLAUDIA CARANGUEJEIRA', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (101, 'PRESIDENT', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (102, 'STANLEY', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (103, 'ANGELENO', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (104, 'BLACK BEAUTY', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (105, 'BLACK STAR', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (106, 'BLACK GOLD', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (107, 'BLACK DIAMOND', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (108, 'BLACK AMBER', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (109, 'BLACK SPLENDOR', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (110, 'FORTUNA', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (111, 'FRIAR', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (112, 'EL DORADO', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (113, 'ELEPHANT HEART', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (114, 'GOLDEN JAPAN', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (115, 'HARRY PITCHON', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (116, 'LAETITIA', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (117, 'METLEY', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (118, 'MIRABELLE DE NANCY', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (119, 'QUEEN ROSE', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (120, 'RED BEAUT', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (121, 'SANTA ROSA', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (122, 'SHIRO', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (123, 'SUNGOLD', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (124, 'WILSON PERFECTION', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (125, 'AUTUMN GIANT', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 1);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (126, 'BULIDA', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 2);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (127, 'CANINO', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 2);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (128, 'LIABAUD', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 2);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (129, 'MAILLOT JAUNE', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 2);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (130, 'POLONAIS', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto', 2);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (131, 'AKANE', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (132, 'BELGOLDEN', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (133, 'BRAVO DE ESMOLFE', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (134, 'CASA NOVA DE ALCOBAÇA', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (135, 'EROVAN', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (136, 'FUJI', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (137, 'GRANNY SMITH', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (138, 'GOLDEN DELICIOUS', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (139, 'HI-EARLY', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (140, 'JONAGORED', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (141, 'LYSGOLDEN', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (142, 'MUTSU', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (143, 'PORTA DA LOJA', 'Janeiro', 'Abril a maio', 'Novembro a dezembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (144, 'REINETTE OU CANADA', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (145, 'REINETTE OU GRAND FAY', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (146, 'RISCADINHA DE PALMELA', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (147, 'ROYAL GALA', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (148, 'REDCHIEF', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (149, 'STARKING', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (150, 'SUMMER RED', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (151, 'WELLSPUR DELICIOUS', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (152, 'NOIVA', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (153, 'OLHO ABERTO', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (154, 'CAMOESA ROSA', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (155, 'MALÁPIO', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (156, 'GRONHO DOCE', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (157, 'PÉ DE BOI ', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (158, 'PINOVA', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (159, 'PARDO LINDO', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (160, 'PIPO DE BASTO', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (161, 'PRIMA', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (162, 'QUERINA', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (163, 'VISTA BELLA', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (164, 'GOLDEN SMOOTHEE', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (165, 'GOLDEN SUPREMA', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (166, 'GLOSTER 69', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (167, 'FREEDOM', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro', 3);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (168, 'SNINSEIKI', '', '', '', 4);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (169, 'KUMOI', '', '', '', 4);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (170, 'HOSUI', '', '', '', 4);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (171, 'NIJISSEIKI', '', '', '', 4);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (184, 'COBRANÇOSA', '', '', 'Outubro a novembro', 11);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (185, 'ARBEQUINA', '', '', 'Outubro a novembro', 11);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (186, 'HOJIBLANCA', '', '', 'Outubro a novembro', 11);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (187, 'NEGRINHA DO FREIXO', '', '', 'Outubro a novembro', 11);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (188, 'PICUAL', '', '', 'Outubro a novembro', 11);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (189, 'MAÇANILHA', '', '', 'Outubro a novembro', 11);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (190, 'CONSERVA DE ELVAS', '', '', 'Outubro a novembro', 11);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (191, 'GALEGA', '', '', 'Outubro a novembro', 11);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (193, 'Dona Maria', 'Dezembro a janeiro', 'Maio', 'Junho a agosto', 12);
INSERT INTO Variedade_Permanente(id, nome, fase_poda, fase_floracao, fase_colheita, cultura_id) VALUES (194, 'Cardinal', 'Dezembro a janeiro', 'Maio', 'Junho a agosto', 12);

INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (172,'Carson Hybrid', '', '80 dias', 5);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (173,'Red Cored Chantenay', '', '80 dias', 5);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (174,'Danvers Half Long', '', '80 dias', 5);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (175,'Imperator 58', '', '80 dias', 5);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (176,'Sugarsnax Hybrid', '', '80 dias', 5);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (177,'Nelson Hybrid', '', '80 dias', 5);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (178,'Scarlet Nantes', '', '80 dias', 5);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (179,'Amarelo', '', '', 6);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (180,'Branco', '', '', 6);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (181,'MAS 24.C', 'Abril a junho', 'Julho a setembro', 8);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (182,'Doce Golden Bantam', 'Abril a junho', 'Julho a setembro', 8);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (183,'Senhora Conceição', 'Março a setembro', 'Junho a fevereiro', 9);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (192,'S. Cosme', 'Fevereiro a abril, agosto a outubro', '90 dias', 10);
INSERT INTO Variedade_Temporaria(id, nome, fase_sementeira, fase_colheita,cultura_id) VALUES (,'Butternut', '', '', 13);
