INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (1, 'Abóbora Manteiga', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (2, 'Maçã Royal Gala', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (3, 'Maçã Jonagored', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (4, 'Maçã Fuji', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (5, 'Maçã Canada', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (6, 'Maçã Grand Fay', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (7, 'Maçã Pipo de Basto', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (8, 'Maçã Gronho Doce', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (9, 'Maçã Malápio', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (10, 'Maçã Porta da Loja', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (11, 'Arbequina', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (12, 'Picual', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (13, 'Galega', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (14, 'Cenoura Sugarsnax Hybrid', ?);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (15, 'Cenoura Danvers Half Long', ?);