@startuml
'https://plantuml.com/class-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods


class Agent

class Adress{
street
}
class City
class District
class State
class ZipCode

class Advertisement{
responsible agent
price
comission type
comission
publication date
}
class Date{
day
month
year
}
class Sale
class Lease

class Property{
area
distance from city center
}
class Land
class ResidentialProperty{
number of bedrooms
number of bathrooms
number of parking spaces
central heating
air conditioning
}
class Apartment
class House{
basement
inhabitable loft
sun exposure
}

Advertisement<|--Sale
Advertisement<|-r-Lease
Advertisement"1"-->"1"Property:describes
Agent"1"-->"*"Advertisement:publishes

Property"1"-->"1"Adress:has an
Property<|-d-Land
Property<|-d-ResidentialProperty
ResidentialProperty<|--Apartment
ResidentialProperty<|--House

Adress"*"-->"1"City:is part of
Adress"*"-->"1"ZipCode:has
City"*"-->"1"District:is part of
District"*"-->"1"State:is part of

Advertisement"1"-l>"1"Date:has a

@enduml