INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (1, 'Abóbora Manteiga', 96);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (2, 'Maçã Royal Gala', 48);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (3, 'Maçã Jonagored', 41);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (4, 'Maçã Fuji', 37);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (5, 'Maçã Canada', 97);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (6, 'Maçã Grand Fay', 98);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (7, 'Maçã Pipo de Basto', 61);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (8, 'Maçã Gronho Doce', 57);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (9, 'Maçã Malápio', 56);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (10, 'Maçã Porta da Loja', 44);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (11, 'Azeitona Arbequina', 86);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (12, 'Azeitona Picual', 89);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (13, 'Azeitona Galega', 92);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (14, 'Cenoura Sugarsnax Hybrid', 77);
INSERT INTO PRODUTO (ID, NOME, VARIEDADE_ID)
VALUES (15, 'Cenoura Danvers Half Long', 75);